name: genome-loader
channels:
  - bioconda
  - conda-forge
  - pytorch
  - nvidia
  - nodefaults
dependencies:
  - attrs
  - ipykernel
  - cyvcf2 # optional
  - dask
  - htslib
  - joblib
  - natsort
  - numba
  - numpy
  - pandas
  - pandera
  - polars>=0.19.3
  - pgenlib # optional
  - poetry
  - pyensembl
  - pyarrow
  - pybigwig
  - pysam
  - python>=3.8.*
  - pytorch
  - pytorch-cuda
  - torchvision 
  - torchaudio
  - ray-default
  - tabix
  - tiledb::tiledbvcf-py # optional
  - xarray
  - pip
  - pip:
    - genvarloader
