name: vep_protein
channels:
    - conda-forge  
    - bioconda
    - nvidia
dependencies:
    - python>=3.9.0
    - pandas
    - numpy
    - openpyxl
    - tqdm
    - umap-learn
    - IProgress
    - ipywidgets
    - pyfaidx
    - pysam
    - HTSeq
    - plotly
    - seaborn
    - scikit-learn
    - biopython
    - pyensembl 
    - biotite
    - owlready2
    - pooch
    - pip
    - pip:
        - torch 
        - torchvision 
        - torchaudio
        # - fair-esm[esmfold] # Old ESM module
        - esm # New ESM module
        - logomaker
        - ensembl-rest
        - gprofiler