name: vep_protein
channels:
    - conda-forge  
    - bioconda
    - pytorch
    - nvidia
dependencies:
    - python>=3.9.0
    - pandas
    - numpy
    - openpyxl
    - tqdm
    - torch
    - umap-learn
    - IProgress
    - ipywidgets
    - bioconda
    - pyfaidx
    - pysam
    - HTSeq
    - plotly
    - seaborn
    - scikit-learn
    - biopython
    - gprofiler
    - pyensembl
    - ensembl-vep
    - biotite
    - owlready2
    - pip
    - pip:
        - fair-esm[esmfold]
        - logomaker