import os
import glob
import pandas as pd
from tqdm.auto import tqdm

import src.utils as utils 
import src.config as config




def get_zenodo(datasets: str = ['1KG',
                                'HRC',
                                'HPRC'],
            progressbar: bool = True,
               **kwargs):
    """
    Download precomputed haplotype results generated by ProHap.
    1000 Genomes Porject (1KG) results from:
         https://zenodo.org/records/12671237
    Human Reference Consortium (HRC) results from:
         https://zenodo.org/records/12671302
    Human Pangenome Reference Consortium (HPRC) results from:
         https://zenodo.org/records/12686819
    """
    import pooch
    files = {}
    processor = pooch.Untar()
    # 1KG 
    if '1KG' in datasets:
        files['1KG'] = {}
        files['1KG']['data'] = pooch.retrieve(
            url="doi:10.5281/zenodo.12671237/240527_ProHap_ALL.tar.gz",
            known_hash="md5:0979e06586bb480c54fbf63ed06d46ed",
            processor=processor,
            progressbar=progressbar,
            fname='240527_ProHap_ALL.tar.gz',
            **kwargs
        ) 
        files['1KG']['config'] = pooch.retrieve(
            url="doi:10.5281/zenodo.12671237/config_ALL_240527.yaml",
            known_hash="md5:634a9a52309fe3b8bafce52a7159b816",
            progressbar=progressbar,
            fname='config_ALL_240527.yaml',
            **kwargs
        )
    # HRC
    if 'HRC' in datasets:
        files['HRC'] = {}
        files['HRC']['data'] = pooch.retrieve(
            url="doi:10.5281/zenodo.12671302/240703_HRC1.1_GRCh38.tar.gz",
            known_hash="md5:96740e94a100738b5ac9bc4dc3af5362",
            processor=processor,
            progressbar=progressbar,
            fname='240703_HRC1.1_GRCh38.tar.gz',
            **kwargs
        )
        files['HRC']['config'] = pooch.retrieve(
            url="doi:10.5281/zenodo.12671302/config_240703_HRC.yaml",
            known_hash="md5:9138e552459a211bdaa6f81d11300c18",
            progressbar=progressbar,
            fname='config_240703_HRC.yaml',
            **kwargs
        )
    # HPRC
    if 'HPRC' in datasets:
        files['HPRC'] = {}
        files['HPRC']['data'] = pooch.retrieve(
            url="doi:10.5281/zenodo.12686819/240703_ProHap_pangenome_ALL.tar.gz",
            known_hash="md5:3af7be4375a9ada3c0458579cafc3283",
            processor=processor,
            progressbar=progressbar,
            fname='240703_ProHap_pangenome_ALL.tar.gz',
            **kwargs
        )
        files['HPRC']['config'] = pooch.retrieve(
            url="doi:10.5281/zenodo.12686819/config_pangenome.yaml",
            known_hash="md5:99152a697966daa67f7cfa3b19d4d915",
            progressbar=progressbar,
            fname='config_pangenome.yaml',
            **kwargs
        )

    return files