import os
import pandas as pd
import argparse
import pathlib 
from tqdm.auto import tqdm

# Local imports
from src.config import DATA_DIR
import src.utils as utils
import src.haplosaurus as hs
import src.predict_esm as ESMp
import src.ESM as ESM
import src.gprofiler as gp
import src.proteingym as pg


def list_models():
    """Get available ESM models.

    This function returns a list of available ESM models that can be used for variant effect prediction.
    It uses the ESM.list_models() function to get models with the 'esm' prefix.

    Returns:
        list: List of available ESM model names as strings.
            For example: ['esm1v_t33_650M_UR90S_1', 'esm1b_t36_3B_UR50D', ...]
    """
    models = []
    # ESM models
    models += ESM.list_models(return_list=True)
    # Other models TBD...
    # ....

    return models


def list_scoring_strategies(models: list[str] = None):
    """Get available scoring strategies for each available model.

    This function returns a dictionary mapping each model to its available scoring strategies.

    Returns:
        dict: Dictionary mapping model names to lists of available scoring strategies.
            For example:
            {
                "esm1v_t33_650M_UR90S_1": ["wt-marginals", "masked-marginals", "pseudo-ppl"],
                "esm1b_t36_3B_UR50D": ["wt-marginals", "masked-marginals", "pseudo-ppl"]
            }
    """
    scoring_strategies = {}
    # ESM models
    scoring_strategies.update(ESM.list_scoring_strategies())
    # Other models TBD...
    # ....

    # Filter by models if provided
    if models is not None:
        scoring_strategies = {k:v for k,v in scoring_strategies.items() if k in models}
    return scoring_strategies   

def vep_pipeline(prot_df: pd.DataFrame = None, 
                 models: list[str] = ["esm1v_t33_650M_UR90S_1"],
                 scoring_strategies: dict[str, list[str]] = None,
                 protein_ids: list[str] = None,
                 source_types: list[str] = None,
                 haplotypes: dict[str, dict[str, str]] = None, 
                 hap_dir: str = hs.DIR_DICT["haplotypes"],
                 save_dir: str = os.path.join(DATA_DIR,"1KG","vep"), 
                 force: bool = False,
                 encode_haplotype_name_threshold: int = 10,
                 mutation_col="mutant",
                 verbose: bool = True):
    """Run ESM variant effect prediction pipeline on protein sequences.

    This script generates a mutational landscape by running ESM variant effect prediction
    on protein sequences and their variants. It uses the predict_esm.py script from:
    https://github.com/facebookresearch/esm/blob/main/examples/variant-prediction/predict.py

    The results are saved in a folder structure:
    {save_dir}/
      {model}/
        {protein_id}/
          {haplotypes}/
            {source_type}/
              {scoring_strategy1}.csv.gz
              {scoring_strategy2}.csv.gz
              {scoring_strategy3}.csv.gz

    Args:
        prot_df (pd.DataFrame): DataFrame containing protein IDs and paths to their respective variant files. If not provided, the function will download a default DataFrame from ProteinGym.
        models (list, optional): List of models to use. Defaults to ["esm1v_t33_650M_UR90S_1"].
        scoring_strategies (dict, optional): Dictionary of scoring strategies for each model. Defaults to None, which will use the default scoring strategies in `list_scoring_strategies`.
        protein_ids (list, optional): List of protein IDs to process. Defaults to None.
        source_types (list, optional): List of variant source types to process (e.g. "clinical_ProteinGym_substitutions", "clinical_ProteinGym_indels"). Defaults to None, which will process all source types.
        haplotypes (dict, optional): Nested dictionary of haplotypes generated by Haplosaurus and imported with `hs.get_haplotypes`. Defaults to None.
        save_dir (str, optional): Directory to save results. Defaults to `config.DATA_DIR/1KG/vep`.
        force (bool, optional): Force recomputation of existing results. Defaults to False.
        encode_haplotype_name_threshold (int, optional): The number of variants in the haplotype name at which to encode the haplotype name using the `encode_haplotype_name` function. 
        Useful for avoiding excessively long file paths. Defaults to 10.
        mutation_col (str, optional): The column name of the mutation column in the input file (i.e. the column that contains values like "A123G" or "A123del"). Defaults to "mutant".
        verbose (bool, optional): Print verbose output. Defaults to True.

    Returns:
        dict: Dictionary mapping (protein_id, sequence_name, scoring_strategy) to output paths

    Example:
        vep_pipeline(models = ["esm1v_t33_650M_UR90S_1"],
                     scoring_strategies = {"esm1v_t33_650M_UR90S_1":["wt-marginals", "masked-marginals"]},
                     protein_ids = ["NP_000509.1"],
                     source_types = ["clinical_ProteinGym_substitutions"],
                     )
    """
    
    # Check models
    models = _check_models(models)
    
    # Check protein ids
    if protein_ids is not None:
        if isinstance(protein_ids, str):
            protein_ids = [protein_ids]

    # Check source types
    if source_types is not None:
        if isinstance(source_types, str):
            source_types = [source_types]
    
    # Scoring strategy
    scoring_strategies = _check_scoring_strategies(scoring_strategies, models)

    # Get mutation data (even if not provided)
    prot_df = _check_prot_df(prot_df=prot_df) 

    # Get haplotypes (even if not provided)
    haplotypes = _check_haplotypes(haplotypes=haplotypes,  
                                   hap_dir=hap_dir, 
                                   verbose=verbose)
    
    # Get haplotype sequences
    hap_seqs = _check_hap_seqs(haplotypes=haplotypes,  
                               verbose=verbose)
    
    # Filter prot_df
    prot_df = filter_prot_df(prot_df=prot_df, 
                          protein_ids=protein_ids, 
                          source_types=source_types, 
                          haplotypes=haplotypes)
    
    # Save paths
    save_paths = {}
    # Iterate over models
    for model_location in models:

        # Get scoring strategies for this model
        scoring_strategy = scoring_strategies[model_location]

        _check_scoring_strategy(scoring_strategy, verbose=verbose)
        
        # Iterate over proteins
        for pid in tqdm(prot_df['protein'].unique().tolist(),
                         desc="Processing proteins"):
            
            assert 'protein' in prot_df.columns
            prot_df_i = prot_df.loc[prot_df['protein']==pid]
            assert len(prot_df_i)>0
            
            # Map protein id to ensp_id
            enst_id = prot_df_i['ENST_haplosaurus'].tolist()[0]
            assert len(enst_id)>0
            ensp_id = prot_df_i['ENSP_haplosaurus'].tolist()[0]
            assert len(ensp_id)>0

            # Iterate over variant types (eg. substitutions, indels)
            for _, row in prot_df_i.iterrows():
                # print(prot_df_i)

                # Get path to variant file
                variants_path = row['source_file']
                assert os.path.exists(variants_path)
                
                # Get source type
                variants_type = row['source_type']
                    
                # Iterate over haplotypes
                for seq_name, seqs in tqdm(hap_seqs[enst_id], 
                                        desc="Processing haplotypes", 
                                        leave=False):
                    print(seq_name)
                    print(seqs)

                    is_ref = seq_name.endswith('REF')
                    assert len(seq_name)>0
                    assert len(seqs)>0

                    # Summarise really long seq_name
                    if seq_name.count(",")>encode_haplotype_name_threshold: # More than X mutations
                        seq_name_save = utils.encode_haplotype_name(seq_name)
                    else:
                        seq_name_save = seq_name
                        
                    if not _check_seq_len(seqs, model_location, pid, seq_name, verbose=verbose):
                        continue
                    
                    # Convert to MultipleSequenceAlignment so we can inject mutations at the correct positions
                    msa = utils.as_msa(seqs) 
                    assert len(msa)>0
                    
                    # Iterate over scoring strategies
                    for ss in tqdm(scoring_strategy,
                                desc="Processing scoring strategies",
                                leave=False): 
                        
                        # create save path
                        save_path = os.path.join(save_dir, 
                                                 model_location, 
                                                 pid, 
                                                 seq_name_save,
                                                 variants_type,
                                                 f"{ss}.csv.gz")
                        save_paths[(pid, seq_name, ss)] = save_path

                        # Skip if file exists and force is False
                        if os.path.exists(save_path) and not force:
                            continue
                        else:
                            os.makedirs(os.path.dirname(save_path), exist_ok=True)

                        # Run VEP
                        ## ESM models
                        if model_location.startswith('esm'):
                            ESMp.main(
                                dms_input=variants_path,
                                dms_output=save_path,
                                model_location=[model_location],
                                sequence=msa,
                                mutation_col=mutation_col,
                                offset_idx=1,
                                scoring_strategy=ss,
                                is_ref=is_ref, 
                                force=force
                            )
                        else:
                            raise ValueError(f"Model {model_location} not supported")
    return save_paths


def _check_models(models: list[str],
                  error: bool = True):
    # Preprocess models
    if isinstance(models, str):
        models = [models]
    models = list(set(models))
    models = [m.strip() for m in models]

    # Check models
    unsupported_models = []
    for model in models:
        if model not in list_models():
            unsupported_models.append(model)
    if len(unsupported_models)>0:
        txt = f"Model(s) not supported: '{','.join(unsupported_models)}'"
        if error:
            raise ValueError(txt)
        else:
            print(txt)
        models = [m for m in models if m not in unsupported_models]

    # Return models
    assert len(models)>0
    return models

def _check_seq_len(seqs: list,
                   model_location: str, 
                   pid: str,
                   seq_name: str,
                   model_checks: dict = {'esm1v':1024,
                                         'esm1b':1024},
                   verbose: bool = True) -> bool:
    """Check if sequence length is compatible with model constraints.
    
    Args:
        seqs (list): List of sequences, where seqs[1] contains the sequence to check
        model_location (str): Name/path of the model being used
        pid (str): Protein ID
        seq_name (str): Name of the sequence
        model_checks (dict): Dictionary mapping model prefixes to their maximum sequence lengths
        verbose (bool): Whether to print warning messages
        
    Returns:
        bool: True if sequence length is compatible, False otherwise
        
    Notes:
        ESM1b/v models cannot handle sequences longer than 1024 residues
        See: https://github.com/facebookresearch/esm/issues/166
    """
    seq_len = len(ESMp.preprocess_sequence(seqs[1]))
    for model, max_len in model_checks.items():
        if model_location.startswith(model) and seq_len > max_len:
            if verbose:
                print(f"Skipping {pid} {seq_name} because sequence is too long for model '{model_location}' ({seq_len} > {max_len})")
            return False
    return True

def _check_scoring_strategy(scoring_strategy: list[str],
                            verbose: bool = True):
    if "pseudo-ppl" in scoring_strategy and verbose:
        print("Warning: scoring_strategy='pseudo-ppl' can take significant compute for large protein sequences, as it considers the entire sequence at once.") 


def _check_prot_df(prot_df) -> pd.DataFrame:
    # Get mutation data
    if prot_df is None:
        prot_df = pg.merge_resources()
    
    assert isinstance(prot_df, pd.DataFrame)
    assert len(prot_df)>0
    assert 'source_file' in prot_df.columns
    assert 'source_type' in prot_df.columns
    assert 'protein' in prot_df.columns
    return prot_df

def _check_haplotypes(haplotypes: dict[str, dict[str, str]],
                      hap_dir: str = os.path.join(DATA_DIR,"1KG","haplotypes"),
                      verbose: bool = True):
    if haplotypes is None:
        if hap_dir is None:
            raise ValueError(" When `haplotypes` is not provided, `hap_dir` must be set.")
        if verbose:
            print(f"`haplotypes` not provided. Importing haplotype sequences from '{hap_dir}'")
        haplotypes = hs.get_haplotypes(save_dir=hap_dir,
                                        cache_only=True,
                                        verbose=verbose)
    return haplotypes

def _check_hap_seqs(haplotypes,  
                    verbose=True):
    hap_seqs = hs.get_haplotype_seqs(haplotypes, 
                                        aligned=2, 
                                        add_haplotype_names=True,
                                        verbose=verbose)
    assert isinstance(hap_seqs, dict)
    assert len(hap_seqs)>0
    return hap_seqs

def filter_prot_df(prot_df: pd.DataFrame,
                  protein_ids: list[str] = None,
                  source_types: list[str] = None,
                  haplotypes: dict[str, dict[str, str]] = None) -> pd.DataFrame:
    
    # Filter by protein ids if provided
    if protein_ids is not None:
        prot_df = prot_df.loc[prot_df['protein'].isin(protein_ids)]
    assert len(prot_df)>0

    # Filter by haplotypes if provided
    if haplotypes is not None:
        # Map ENP IDs
        hap_seqs_id_map = gp.get_id_map(ids=haplotypes.keys(),
                                        rename_converted=True,
                                        target_namespace='ENST',
                                        as_dict=-1)
        
        # Map prot_df
        prot_df = pg.map_resources(prot_df)
        # Map ENST to ENSP
        prot_df.loc[:,'ENST_haplosaurus'] = prot_df['ENST'].map(hap_seqs_id_map)
        enst_to_ensp = hs.get_haplotype_protein_ids(haplotypes)
        prot_df.loc[:,'ENSP_haplosaurus'] = prot_df['ENST_haplosaurus'].map(enst_to_ensp)

        # Filter the prot_df
        prot_df = prot_df.loc[prot_df['ENST_haplosaurus'].notna()]  
        if source_types is not None:
            prot_df = prot_df.loc[prot_df['source_type'].isin(source_types)]
        
        # Only keep the first occurence of each experiment_id (to avoid artifacts of ID mapping)
        prot_df = prot_df.drop_duplicates(subset=['experiment_id']) 
        
        # Report the number of unique proteins 
        print(len(prot_df['protein'].unique()),"unique proteins") 
    
    assert 'ENST_haplosaurus' in prot_df.columns
    assert 'ENSP_haplosaurus' in prot_df.columns
    # Return the filtered prot_df
    assert len(prot_df)>0
    return prot_df


def _parse_scoring_strategies(scoring_strategies):
    """
    Parse scoring strategies from command line argument
    
    Example:
        scoring_strategies = "esm1v_t33_650M_UR90S_1:wt-marginals,masked-marginals,pseudo-ppl;esm1b_t36_3B_UR50D:wt-marginals"
        _parse_scoring_strategies(scoring_strategies)
        returns:
        {
            "esm1v_t33_650M_UR90S_1": ["wt-marginals", "masked-marginals", "pseudo-ppl"],
            "esm1b_t36_3B_UR50D": ["wt-marginals"]
        }
    """
    result = {}
    # Split by model groups
    model_groups = scoring_strategies.split(";")
    for group in model_groups:
        # Split model name from strategies
        model, strategies = group.split(":")
        # Strip whitespace
        model = model.strip()
        strategies = strategies.strip()
        # Split strategies into list
        result[model] = strategies.split(",")
    return result

def _check_scoring_strategies(scoring_strategies,
                              models):
    if scoring_strategies is None:
        scoring_strategies = ESM.list_scoring_strategies()
    for model in models:
        if model not in scoring_strategies:
            raise ValueError(f"Model {model} not found in scoring_strategies")
    return scoring_strategies


def _parse_args():
    parser = argparse.ArgumentParser(description="Run ESM variant effect prediction pipeline on protein haplotype sequences.")
    parser.add_argument("--prot_df", 
                        type=pathlib.Path, 
                        required=True,
                        help="Path to CSV file containing protein IDs and metadata. Will be imported with `pandas.read_csv`.")
    parser.add_argument("--protein_ids",
                        type=str, 
                        required=False,
                        help="Comma-separated list of protein IDs to process. If not provided, all protein IDs in prot_df will be processed."
                        )
    parser.add_argument("--hap_dir",
                        type=pathlib.Path,
                        required=False,
                        default=os.path.join(DATA_DIR,"1KG","haplotypes"),
                        help="Directory where haplotype sequences are stored. If not provided, haplotypes will be imported from the defaulthaplotypes directory in the `DATA_DIR`.")
    parser.add_argument("--models", 
                        type=str, 
                        required=True, 
                        choices=list_models(),
                        default="esm1v_t33_650M_UR90S_1",
                        help="Protein sequence model(s) to use for generating predictions.")
    parser.add_argument("--scoring_strategies", 
                        type=str, 
                        required=True,
                        default="esm1v_t33_650M_UR90S_1:wt-marginals,masked-marginals,pseudo-ppl",
                        help="Model-specific scoring strategies in format 'model1:strat1,strat2;model2:strat1,strat2'")
    parser.add_argument("--force", 
                        type=bool, 
                        required=False,
                        default=False,
                        help="Force recomputation of existing results.")
    parser.add_argument("--save_dir", 
                        type=pathlib.Path,
                        required=False,
                        default=os.path.join(DATA_DIR,"1KG","vep"),
                        help="Directory to save results.")
    parser.add_argument("--verbose", type=bool, default=True,
                       help="Print verbose output.")
    return parser.parse_args()


#### MAIN FUNCTION ####
if __name__ == "__main__":

    # Parse arguments
    args = _parse_args()
    prot_df = pd.read_csv(args.prot_df)
    scoring_strategies = _parse_scoring_strategies(args.scoring_strategies)
    
    # Run pipeline
    vep_pipeline(prot_df, 
                 models = args.models,
                 scoring_strategies = scoring_strategies,
                 hap_dir = args.hap_dir,
                 save_dir = args.save_dir,
                 force = args.force,
                 verbose = args.verbose)
